# Generated by Django 4.2 on 2023-07-06 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_site_delete_submittedurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('excerpt', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('post_date', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader.site')),
            ],
        ),
    ]
