# Generated by Django 4.2 on 2023-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='feed_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
