# Generated by Django 4.1.7 on 2023-07-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_alter_post_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_icon',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
