# Generated by Django 4.2 on 2023-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0010_post_site_icon_post_site_name_post_site_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="site_icon",
            field=models.ImageField(blank=True, null=True, upload_to="site_icons/"),
        ),
        migrations.AlterField(
            model_name="site",
            name="feed_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
