# Generated by Django 4.2 on 2023-12-11 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0012_remove_post_tags_tagulous_post_topics_post_topics"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tagulous_Post_topics",
            new_name="Topics",
        ),
    ]
