# Generated by Django 4.2 on 2023-12-12 11:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0016_tool_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
