# Generated by Django 4.2 on 2023-12-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0019_alter_post_site_name_alter_post_site_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="title",
            field=models.CharField(max_length=600),
        ),
    ]
