# Generated by Django 4.2 on 2023-12-12 18:29

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0022_sitecategory_site_site_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteCategory",
            new_name="SiteType",
        ),
        migrations.RemoveField(
            model_name="site",
            name="site_category",
        ),
        migrations.AddField(
            model_name="site",
            name="site_type",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                help_text="Enter a comma-separated tag string",
                null=None,
                to="reader.sitetype",
            ),
        ),
    ]
