# Generated by Django 4.2 on 2023-12-12 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0023_rename_sitecategory_sitetype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitetype",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="sitetype",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
