# Generated by Django 4.2 on 2023-12-12 20:08

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0025_site_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_type",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                help_text="Enter a comma-separated tag string",
                to="reader.sitetype",
            ),
        ),
    ]
