# Generated by Django 4.2 on 2023-12-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0026_alter_site_site_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
