# Generated by Django 4.2 on 2023-12-12 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0027_alter_site_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="slug",
            new_name="site_slug",
        ),
    ]
