# Generated by Django 4.2 on 2023-12-12 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0028_rename_slug_site_site_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="site_slug",
            new_name="slug",
        ),
    ]
