# Generated by Django 4.2 on 2023-12-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0029_rename_site_slug_site_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
