# Generated by Django 4.2 on 2023-12-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0031_site_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="include_in_newsfeed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="site",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
