# Generated by Django 4.2 on 2023-12-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0032_site_include_in_newsfeed_alter_site_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
