# Generated by Django 4.2 on 2023-12-12 22:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0034_alter_site_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="site_icon",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
