# Generated by Django 4.2 on 2023-12-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0035_alter_site_site_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='site_icon',
        ),
        migrations.RemoveField(
            model_name='post',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='site_title',
        ),
    ]
