# Generated by Django 4.2 on 2023-12-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0036_remove_post_categories_remove_post_site_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='url',
            new_name='link',
        ),
    ]
