# Generated by Django 4.2 on 2023-12-14 23:55

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0038_post_summary_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='reader.tag'),
        ),
    ]
